### ISSUE TITLE
drmaa library error

### ISSUE THREAD

**Issue by loraine-gueguen** [genouest/docker_elasticsearch_exec#1]
Is there any env variable DRMAA_LIBRARY_PATH available  as for https://github.com/genouest/docker_slurm_exec ?
On abims, wehave the following error with this image:

`OSError: libslurm.so.37: cannot open shared object file: No such file or directory`

**Comment by mboudet** [comment]
Hmm, there should be not interaction with slurm at all, so it's strange

**Comment by loraine-gueguen** [comment]
https://gitlab.sb-roscoff.fr/abims/e-infra/gga_workflow/-/jobs/27095

**Comment by mboudet** [comment]
Unrelated to this image. Issue is with the Beauris library.
(https://gitlab.com/beaur1s/beauris/-/issues/79)
